name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy_type:
        description: 'Deployment type'
        required: false
        default: 'ec2'
      target_env:
        description: 'Target environment'
        required: false
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
